name: Microsoft C++ Code Analysis (src only)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'  # Запускать только при изменениях в src/
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'

jobs:
  analyze:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S src  # Указываем src/ как исходный каталог

      - name: Run MSVC Analysis
        uses: microsoft/msvc-code-analysis-action@v1
        id: run-analysis
        with:
          cmakeBuildDirectory: build
          ruleset: NativeRecommendedRules.ruleset

      - name: Filter SARIF (только src/)
        if: always()  # Фильтруем даже при ошибках
        run: |
          jq '.runs[].results |= map(select(.locations[].physicalLocation.artifactLocation.uri | startswith("src/")))' ${{ steps.run-analysis.outputs.sarif }} > filtered.sarif
          mv filtered.sarif ${{ steps.run-analysis.outputs.sarif }}

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
