name: Lint C++ Code

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.clang-format'
  pull_request:
    branches: [ "master" ]

jobs:
  lint-cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up clang-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Verify config files
        run: |
          [ -f .clang-format ] || { echo ".clang-format not found!"; exit 1; }

      - name: Run clang-format check
        run: |
          find src/ -name '*.cpp' -o -name '*.hpp' | xargs clang-format --style=file --dry-run --Werror

      - name: Run Super-Linter (basic checks)
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CPP: true
          VALIDATE_CLANG_FORMAT: false     
          FILTER_REGEX_INCLUDE: "src/.*"